name: Native Linux

on:
  pull_request:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  unix:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
        rust: [ 1.59.0 ]

    runs-on: ${{matrix.os}}
    env:
      RUST_VERSION: ${{matrix.rust}}
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
      SCCACHE_DIR: $PATH/.cache/sccache

    steps:
    - uses: actions/checkout@v1

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cache/sccache
        key: ${{ runner.os }}-main-${{matrix.rust}}-${{steps.date.outputs.date}}

    - name: "Setup sccache"
      run: .travis/setup-sccache.sh

    - name: Native script
      run: .travis/regular-tests.sh
      env:
        SHORT: yes

    - name: Stop sccache server
      run: sccache --stop-server || true
